params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
stages:
  make_dataset:
    cmd: python ./src/make_dataset.py 
    deps:
    - ./data/raw/creditcard.csv
    - ./src/make_dataset.py
    params:
    - make_dataset.test_split
    - make_dataset.seed
    outs:
    - ./data/processed/
  train_model:
    cmd: python ./src/train_model.py
    deps:
    - ./src/train_model.py
    - ./data/processed/train.csv
    params:
    - train_model.n_estimators
    - train_model.max_depth
    outs:
    - ./models/
